'''import argparse

parser = argparse.ArgumentParser()

parser.add_argument('echo', help='echo the string you use as argument')

args = parser.parse_args()

print(args.echo)

'''
'''import errno

try:
	fp.open('no_such_file.file')
except IOError, (error,message):
	if (error == errno.ENOENT):
		print ('no such file or directory')
	elif (error == errno.EPERM):
		print ('permission denied')
	else:
		print(message)
'''
import logging

FILE_NAME = 'logFile.log'

logging.basicConfig(filename = FILE_NAME, level = logging.DEBUG)

logging.debug('this file store the debug info please do not edit this file:')